### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by Stefie** [housinghq/react-lazy-card#5]
Hi,
I just noticed a small typo in the README file and I don't want to make a pull request for that...

https://github.com/housinghq/react-lazy-card#basic-usage --> JSX

`<LazyCard image="b.jpg" autoLoad={true} defaultimage="default2.jpg">Text 2</LazyCard>`

'defaultimage' is all written in lowercase, but the 'i' should be uppercase -> 'defaultImage'

Thanks for the plugin!

**Comment by azizhk** [comment]
Thank you
